sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0    # 可选：0-15

  # 阿里云OSS配置
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: takeout-judy